list(APPEND SI_SRC
        src/vulkan/VulkanRenderer.cpp
        src/vulkan/Buffer.hpp
        src/vulkan/Buffer.cpp
        src/vulkan/CommandPool.hpp
        src/vulkan/CommandPool.cpp
        src/vulkan/Device.hpp
        src/vulkan/Device.cpp
        src/vulkan/Fence.hpp
        src/vulkan/Fence.cpp
        src/vulkan/Framebuffer.hpp
        src/vulkan/Framebuffer.cpp
        src/vulkan/FrameData.hpp
        src/vulkan/FrameData.cpp
        src/vulkan/Handle.hpp
        src/vulkan/Handle.cpp
        src/vulkan/ImageView.hpp
        src/vulkan/ImageView.cpp
        src/vulkan/Instance.hpp
        src/vulkan/Instance.cpp
        src/vulkan/PhysicalDevice.hpp
        src/vulkan/PhysicalDevice.cpp
        src/vulkan/Pipeline.hpp
        src/vulkan/Pipeline.cpp
        src/vulkan/PipelineLayout.hpp
        src/vulkan/PipelineLayout.cpp
        src/vulkan/RenderPass.hpp
        src/vulkan/RenderPass.cpp
        src/vulkan/RequestableItem.hpp
        src/vulkan/Semaphore.hpp
        src/vulkan/Semaphore.cpp
        src/vulkan/Shader.hpp
        src/vulkan/Shader.cpp
        src/vulkan/Surface.cpp
        src/vulkan/Surface.hpp
        src/vulkan/SwapChain.cpp
        src/vulkan/SwapChain.hpp
        src/vulkan/VMA.cpp)