function(AddModule MODULE_NAME)
    set(LOCAL_MODULE_INCLUDES ${ENGINE_MODULE_INCLUDES})
    set(LOCAL_MODULE_INCLUDE_DIRS ${ENGINE_MODULE_INCLUDE_DIRS})
    set(LOCAL_MODULE_INIT_FUNCS ${ENGINE_MODULE_INIT_FUNCS})
    set(LOCAL_MODULE_DEINIT_FUNCS ${ENGINE_MODULE_DEINIT_FUNCS})
    set(LOCAL_MODULE_SRC ${SI_SRC})
    set(LOCAL_MODULE_DEPS ${SI_DEPENDENCIES})

    string(APPEND LOCAL_MODULE_INCLUDES "#include \"Silicon/${MODULE_NAME}/${MODULE_NAME}.hpp\"\n")
    string(APPEND LOCAL_MODULE_INIT_FUNCS "        Si::${MODULE_NAME}::Initialize();\n")
    string(APPEND LOCAL_MODULE_DEINIT_FUNCS "        Si::${MODULE_NAME}::Deinitialize();\n")

    list(APPEND LOCAL_MODULES ${MODULE_NAME})
    list(APPEND LOCAL_MODULE_INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/src/modules/${MODULE_NAME}/include")
    list(APPEND LOCAL_MODULE_INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/src/modules/${MODULE_NAME}/include/Silicon")

    include("src/${MODULE_NAME}/${MODULE_NAME}.cmake")

    set(ENGINE_MODULE_INCLUDES ${LOCAL_MODULE_INCLUDES} PARENT_SCOPE)
    set(ENGINE_MODULE_INCLUDE_DIRS ${LOCAL_MODULE_INCLUDE_DIRS} PARENT_SCOPE)
    set(ENGINE_MODULE_INIT_FUNCS ${LOCAL_MODULE_INIT_FUNCS} PARENT_SCOPE)
    set(ENGINE_MODULE_DEINIT_FUNCS ${LOCAL_MODULE_DEINIT_FUNCS} PARENT_SCOPE)
    set(SI_SRC ${LOCAL_MODULE_SRC} PARENT_SCOPE)
    set(SI_DEPENDENCIES ${LOCAL_MODULE_DEPS})
    set(${MODULE_NAME} ${MODULE_NAME} PARENT_SCOPE)

    message(STATUS "Building module: ${MODULE_NAME}")
endfunction(AddModule)