function(AddModule MODULE_NAME)
	set(LOCAL_MODULE_INCLUDES ${ENGINE_MODULE_INCLUDES})
	set(LOCAL_MODULE_INIT_FUNCS ${ENGINE_MODULE_INIT_FUNCS})
	set(LOCAL_MODULE_DEINIT_FUNCS ${ENGINE_MODULE_DEINIT_FUNCS})
	set(LOCAL_MODULES ${ENGINE_MODULES})
	
	string(APPEND LOCAL_MODULE_INCLUDES "#include \"${MODULE_NAME}/${MODULE_NAME}.hpp\"\n")
    string(APPEND LOCAL_MODULE_INIT_FUNCS "        ${MODULE_NAME}::Initialize();\n")
    string(APPEND LOCAL_MODULE_DEINIT_FUNCS "        ${MODULE_NAME}::Deinitialize();\n")
	
    list(APPEND LOCAL_MODULES ${MODULE_NAME})
    
    add_subdirectory("src/modules/${MODULE_NAME}")

	set(ENGINE_MODULE_INCLUDES ${LOCAL_MODULE_INCLUDES} PARENT_SCOPE)
	set(ENGINE_MODULE_INIT_FUNCS ${LOCAL_MODULE_INIT_FUNCS} PARENT_SCOPE)
	set(ENGINE_MODULE_DEINIT_FUNCS ${LOCAL_MODULE_DEINIT_FUNCS} PARENT_SCOPE)
	set(ENGINE_MODULES ${LOCAL_MODULES} PARENT_SCOPE)
    set(${MODULE_NAME} ${MODULE_NAME} PARENT_SCOPE)
endfunction(AddModule)